apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: cinemaabyss
  labels:
    app: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: ghcr.io/zverev-ap/architecture-cinemaabyss/events-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
            - secretRef:
                name: cinemaabyss-secrets
          resources:
            limits:
              cpu: "300m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /api/events/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/events/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: cinemaabyss
spec:
  selector:
    app: event-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP