{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
          image: "{{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}"
          imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.proxyService.service.targetPort }}
              name: http
          resources:
            {{- toYaml .Values.proxyService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: proxy-service
  ports:
    - port: {{ .Values.proxyService.service.port }}
      targetPort: {{ .Values.proxyService.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.proxyService.service.type }}
{{- end }}